a=input("请输入证件路径：")
b=input("请输入文件名:")
c=("E:\pythonProject1\day10")
f1 =open(file=a+"\\"+b,mode="rb")
f2 =open(file=c+"aa.jpg",mode="wb")
data=f1.read()
f2.write(data)
print(f2)
f2.close()
f1.close()